---
- name: Converge
  hosts: all

  roles:
    - role: boutetnico.systemd
      systemd_unit_files:
        - name: example-unit
          config:
            Unit:
              Description: Example unit file
            Service:
              ExecStart: /bin/bash -c "while true; do sleep 3600; done"
              Restart: always
              User: root
              Group: root
              LimitNOFILE: 65536
              TimeoutStopSec: 10
            Install:
              WantedBy: multi-user.target
        - name: example-unit-2
          config:
            Unit:
              Description: Second example unit file
            Service:
              ExecStart: /bin/bash -c "while true; do sleep 3600; done"
              Restart: on-failure
              User: root
              Group: root
            Install:
              WantedBy: multi-user.target
